import realSchema from './enum-results-workorder.json' with { type: 'json' }

const tables = {
  workorder: {
    api: '/api/v1/workorder',
    hasPagination: true,
    view: data => `https://app.rekyl.nu/v5/8399/details/workorder/${data.id}`,
    schema: {
      buyerEmail: { type: 'string', label: 'Köparens e-post' },
      city: { type: 'string', label: 'Stad' },
      comment: { type: 'string', label: 'Kommentar' },
      company: { type: 'reference', ref: 'company', label: 'Företag' },
      contactEmail: { type: 'string', label: 'Kontakt E-post' },
      contactPerson: { type: 'string', label: 'Kontaktperson' },
      contactPhone: { type: 'string', label: 'Kontakttelefon' },
      created: { type: 'date', label: 'Datum Skapad' },
      custom1: { type: 'number', label: 'Custom 1' },
      custom3: { type: 'number', label: 'Custom 3' },
      custom2: { type: 'number', label: 'Custom 2' },
      custom4: { type: 'number', label: 'Custom 4', label: 'Jobbtyp' },
      custom5: { type: 'number', label: 'Custom 5' },
      custom6: { type: 'number', label: 'Custom 6' },
      custom7: { type: 'number', label: 'Custom 7' },
      custom8: { type: 'number', label: 'Custom 8' },
      custom9: { type: 'number', label: 'Custom 9' },
      custom10: { type: 'number', label: 'Custom 10' },
      custom11: { type: 'number', label: 'Custom 11' },
      custom12: { type: 'number', label: 'Custom 12' },
      custom13: { type: 'number', label: 'Custom 13' },
      custom14: { type: 'number', label: 'Custom 14' },
      custom15: { type: 'number', label: 'Custom 15' },
      custom16: { type: 'number', label: 'Custom 16' },
      custom17: { type: 'number', label: 'Custom 17' },
      custom18: { type: 'number', label: 'Custom 18' },
      custom19: { type: 'number', label: 'Custom 19' },
      custom20: { type: 'number', label: 'Custom 20' },
      custom21: { type: 'number', label: 'Custom 21' },
      custom22: { type: 'number', label: 'Custom 22' },
      custom23: { type: 'number', label: 'Custom 23' },
      custom24: { type: 'number', label: 'Custom 24' },
      custom25: { type: 'number', label: 'Custom 25' },
      custom26: { type: 'number', label: 'Custom 26' },
      custom27: { type: 'number', label: 'Custom 27' },
      custom28: { type: 'number', label: 'Custom 28' },
      custom29: { type: 'number', label: 'Custom 29' },
      custom30: { type: 'number', label: 'Custom 30' },
      customText1: { type: 'string', label: 'Custom Text 1' },
      customText2: { type: 'string', label: 'Nyckel' },
      customText3: { type: 'string', label: 'Custom Text 3' },
      customText4: { type: 'string', label: 'Port kod' },
      customText5: { type: 'string', label: 'Custom Text 5' },
      customText6: { type: 'string', label: 'Custom Text 6' },
      customText7: { type: 'string', label: 'Custom Text 7' },
      customText8: { type: 'string', label: 'Custom Text 8' },
      customText9: { type: 'string', label: 'Custom Text 9' },
      customText10: { type: 'string', label: 'Custom Text 10' },
      customText11: { type: 'string', label: 'Custom Text 11' },
      customText12: { type: 'string', label: 'Custom Text 12' },
      customText13: { type: 'string', label: 'Custom Text 13' },
      customText14: { type: 'string', label: 'Order titel' },
      customText15: { type: 'string', label: 'Custom Text 15' },
      customText16: { type: 'string', label: 'Custom Text 16' },
      customText17: { type: 'string', label: 'Custom Text 17' },
      customText18: { type: 'string', label: 'Custom Text 18' },
      customText19: { type: 'string', label: 'Custom Text 19' },
      customText20: { type: 'string', label: 'Custom Text 20' },
      customText21: { type: 'string', label: 'Custom Text 21' },
      customText22: { type: 'string', label: 'Custom Text 22' },
      customText23: { type: 'string', label: 'Custom Text 23' },
      customText24: { type: 'string', label: 'Custom Text 24' },
      customText25: { type: 'string', label: 'Custom Text 25' },
      customText26: { type: 'string', label: 'Custom Text 26' },
      customText27: { type: 'string', label: 'Custom Text 27' },
      customText28: { type: 'string', label: 'Custom Text 28' },
      customText29: { type: 'string', label: 'Custom Text 29' },
      customText30: { type: 'string', label: 'Custom Text 30' },
      debitMethod: { type: 'number', label: 'Debiteringsmetod' },
      description: { type: 'string', label: 'Beskrivning' },
      firstScheme: { type: 'string', label: 'Första schema' },
      flags: { type: 'number', label: 'Flaggor' },
      id: { type: 'number', label: 'ID', primary: true, autoincrement: true },
      invoiced: { type: 'date', label: 'Fakturerad' },
      // latitude: { type: 'number', label: 'Latitud', ag: {
      //     // change value getter
      //     valueGetter(params) {
      //       const wo = params.data?.workorder
      //       const pr = params.data?.projectNumber

      //       if (wo?.latitude) {
      //         return wo.latitude
      //       } else if (pr?.latitude) {
      //         return pr.latitude
      //       } else {
      //         return null
      //       }
      //     }
      // } },
      // longitude: { type: 'number', label: 'Longitud', ag: {
      //     // change value getter
      //     valueGetter(params) {
      //       const wo = params.data?.workorder
      //       const pr = params.data?.projectNumber

      //       if (wo?.longitude) {
      //         return wo.longitude
      //       } else if (pr?.longitude) {
      //         return pr.longitude
      //       } else {
      //         return null
      //       }
      //     }
      // } },
      latitude: { type: 'number', label: 'Latitud' },
      longitude: { type: 'number', label: 'Longitud' },
      manager: { type: 'reference', ref: 'salesman', label: 'Handläggare' },
      modified: { type: 'date', label: 'Modifierad' },
      // office: { type: 'reference', ref: 'office', label: 'Kontor' },
      orderMarking: { type: 'string', label: 'Ordermarkering' },
      orderType: { type: 'enum', values: ['Typ1', 'Typ2', 'Typ3'], label: 'Ordertyp' },
      price: { type: 'number', label: 'Pris' },
      project0: { type: 'obsolete' },
      project1: { type: 'obsolete' },
      project2: { type: 'obsolete' },
      salesman: { type: 'reference', ref: 'salesman', label: 'Skapad av' },
      schemeExists: { type: 'string', label: 'Schema finns' },
      splitReference: { type: 'string', label: 'Splitreferens' },
      start: { type: 'date', label: 'Start', required: true },
      status: {
        type: 'enum',
        values: ['Pågående', 'Vilande', 'Avslutad', 'Fakturering', 'Fakturerad', 'Makulerad', 'Ny'],
        label: 'Status',
        ag: {
          editable: true,
          async update(params) {
            console.log(params)
            // const { data, newValue, oldValue } = params
            // console.log({ data, newValue, oldValue })
            // console.log({ params })
            // if (newValue === oldValue) return; // No change

            await new Promise(resolve => setTimeout(resolve, 3000)) // Wait for AG Grid to update the cell value
            return false
          }
        }
      },
      dateTimeWhenStatusChangedToOngoing: { type: 'date', label: 'Datum och tid när status ändrades till Pågående' },
      dateTimeWhenStatusChangedToOnHold: { type: 'date', label: 'Datum och tid när status ändrades till Pausad' },
      dateTimeWhenStatusChangedToCompleted: { type: 'date', label: 'Datum och tid när status ändrades till Slutförd' },
      dateTimeWhenStatusChangedToBilling: { type: 'date', label: 'Datum och tid när status ändrades till Fakturering' },
      dateTimeWhenStatusChangedToInvoiced: { type: 'date', label: 'Datum och tid när status ändrades till Fakturerad' },
      dateTimeWhenStatusChangedToCanceled: { type: 'date', label: 'Datum och tid när status ändrades till Avbruten' },
      dateTimeWhenStatusChangedToNew: { type: 'date', label: 'Datum och tid när status ändrades till Ny' },
      projectNumber: { type: 'reference', ref: 'project', label: 'Projekt' },
      time: { type: 'string', label: 'Tid' },
      timeEnd: { type: 'string', label: 'Sluttid' },
      timeStart: { type: 'string', label: 'Starttid' },
      workingsite: { type: 'string', label: 'Arbetsplats' },
      postcode: { type: 'string', label: 'Postnummer' },
      buyerNameSeparate: { type: 'string', label: 'Köparens namn separat' },
      buyerPhoneSeparate: { type: 'string', label: 'Köparens telefon separat' },
      buyerEmailSeparate: { type: 'string', label: 'Köparens e-post separat' },
      customerNoSeparate: { type: 'string', label: 'Kundnummer separat' },
      customerNo: { type: 'string', label: 'Kundnummer' },
      invoiceNameSeparate: { type: 'string', label: 'Fakturanamn separat' },
      structure: { type: 'number', label: 'Struktur' },
      supplierInvoices: { type: 'number', label: 'Leverantörsfakturor' },
      priceListActual: { type: 'string', label: 'Aktuell prislista' },
      timeLastTimeReport: { type: 'string', label: 'Tid för senaste tidsrapport' },
      assignerSeparate: { type: 'string', label: 'Sep. Kunduppgift.' },
      nonInvoicedSupplierinvoice: { type: 'number', label: 'Ej fakturerad leverantörsfaktura' },
      hours: { type: 'number', label: 'Timmar' },
      preInvoice: { type: 'string', label: 'Förfaktura' },
      externalSystem: { type: 'string', label: 'Externt system' },
      externalReference: { type: 'string', label: 'Extern referens' },
      addTimeReport: {
        // https://app.rekyl.nu/8399/mobil/timereport.asp?show=guide&todo=clear
        type: 'string',
        label: 'Lägg till tidsrapport',
        ag: {
          valueGetter(params) {
            const id = params.data?.workorder?.id
            if (!id) return null
            return 'https://app.rekyl.nu/8399/mobil/timereport.asp?' + new URLSearchParams({
              show: 'guide',
              todo: 'clear',
              time_date: '',
              int_workorder: id,
              gobackurl: `workorders.asp?show=details&time_date=&id=${id}`
            })
          },
          cellRenderer(params) {
            const id = params.data?.workorder?.id
            if (!id) return null

            const link = document.createElement('a')
            // https://app.rekyl.nu/8399/mobil/timereport.asp?show=guide&todo=clear&time_date=&int_workorder=118438&gobackurl=workorders.asp?show=details&time_date=&id=118438
            link.href = 'https://app.rekyl.nu/8399/mobil/timereport.asp?' + new URLSearchParams({
              show: 'guide',
              todo: 'clear',
              time_date: '',
              int_workorder: id,
              gobackurl: `workorders.asp?show=details&time_date=&id=${id}`
            })
            link.target = '_blank'
            link.textContent = 'Skapa tidsrapport'
            return link
          }
        }
      },
      direction: {
        type: 'string',
        label: '➤',
        ag: {
          valueGetter (params) {
            const { latitude, longitude } = params.data?.workorder || {}
            if (!latitude || !longitude) return null
            return 'https://www.google.com/maps/dir/?api=1&destination=' + latitude + ',' + longitude
          },
          cellRenderer(params) {
            const { latitude, longitude } = params.data?.workorder || {}
            if (!latitude || !longitude) return null
            const url = 'https://www.google.com/maps/dir/?api=1&destination=' + latitude + ',' + longitude
            const link = document.createElement('a')
            link.href = url
            link.target = '_blank'
            link.textContent = '➤'

            // rotate text some degrees to indicate it's a link
            link.style.display = 'inline-block'
            link.style.transform = 'rotate(-45deg)'
            link.style.textDecoration = 'none'
            return link
          }
        }
      }
    }
  },
  project: {
    api: '/api/v1/project',
    view: data => `https://app.rekyl.nu/v5/8399/details/project/${data.id}`,
    hasPagination: true,
    schema: {
      custom1: { type: 'number', label: 'Custom 1' },
      custom2: { type: 'number', label: 'Custom 2' },
      custom3: { type: 'number', label: 'Custom 3' },
      custom4: { type: 'number', label: 'Custom 4' },
      custom5: { type: 'number', label: 'Custom 5' },
      custom6: { type: 'number', label: 'Custom 6' },
      custom7: { type: 'number', label: 'Custom 7' },
      custom8: { type: 'number', label: 'Custom 8' },
      custom9: { type: 'number', label: 'Custom 9' },
      custom10: { type: 'number', label: 'Custom 10' },
      custom11: { type: 'number', label: 'Custom 11' },
      custom12: { type: 'number', label: 'Custom 12' },
      custom13: { type: 'number', label: 'Custom 13' },
      custom14: { type: 'number', label: 'Custom 14' },
      custom15: { type: 'number', label: 'Custom 15' },
      custom16: { type: 'number', label: 'Custom 16' },
      custom17: { type: 'number', label: 'Custom 17' },
      custom18: { type: 'number', label: 'Custom 18' },
      custom19: { type: 'number', label: 'Custom 19' },
      custom20: { type: 'number', label: 'Custom 20' },
      custom21: { type: 'number', label: 'Custom 21' },
      custom22: { type: 'number', label: 'Custom 22' },
      custom23: { type: 'number', label: 'Custom 23' },
      custom24: { type: 'number', label: 'Custom 24' },
      custom25: { type: 'number', label: 'Custom 25' },
      custom26: { type: 'number', label: 'Custom 26' },
      custom27: { type: 'number', label: 'Custom 27' },
      custom28: { type: 'number', label: 'Custom 28' },
      custom29: { type: 'number', label: 'Custom 29' },
      custom30: { type: 'number', label: 'Custom 30' },
      customText1: { type: 'string', label: 'Custom Text 1' },
      customText2: { type: 'string', label: 'Custom Text 2' },
      customText3: { type: 'string', label: 'Custom Text 3' },
      customText4: { type: 'string', label: 'Custom Text 4' },
      customText5: { type: 'string', label: 'Custom Text 5' },
      customText6: { type: 'string', label: 'Custom Text 6' },
      customText7: { type: 'string', label: 'Custom Text 7' },
      customText8: { type: 'string', label: 'Custom Text 8' },
      customText9: { type: 'string', label: 'Custom Text 9' },
      customText10: { type: 'string', label: 'Custom Text 10' },
      customText11: { type: 'string', label: 'Custom Text 11' },
      customText12: { type: 'string', label: 'Custom Text 12' },
      customText13: { type: 'string', label: 'Custom Text 13' },
      customText14: { type: 'string', label: 'Custom Text 14' },
      customText15: { type: 'string', label: 'Custom Text 15' },
      customText16: { type: 'string', label: 'Custom Text 16' },
      customText17: { type: 'string', label: 'Custom Text 17' },
      customText18: { type: 'string', label: 'Custom Text 18' },
      customText19: { type: 'string', label: 'Custom Text 19' },
      customText20: { type: 'string', label: 'Custom Text 20' },
      customText21: { type: 'string', label: 'Custom Text 21' },
      customText22: { type: 'string', label: 'Custom Text 22' },
      customText23: { type: 'string', label: 'Custom Text 23' },
      customText24: { type: 'string', label: 'Custom Text 24' },
      customText25: { type: 'string', label: 'Custom Text 25' },
      customText26: { type: 'string', label: 'Custom Text 26' },
      customText27: { type: 'string', label: 'Custom Text 27' },
      customText28: { type: 'string', label: 'Custom Text 28' },
      customText29: { type: 'string', label: 'Custom Text 29' },
      customText30: { type: 'string', label: 'Custom Text 30' },
      projectNumber: { type: 'string', label: 'Projekt #', primary: true, unique: true },
      accruedAcontoIncome: { type: 'number', label: 'Ackumulerad Acontoinkomst' },
      accruedArticleCost: { type: 'number', label: 'Ackumulerad Artikekostnad' },
      accruedArticleIncome: { type: 'number', label: 'Ackumulerad Artikelinkomst' },
      accruedArticleOverhead: { type: 'number', label: 'Ackumulerad Artikelomkostnad' },
      accruedCalculusIncome: { type: 'number', label: 'Ackumulerad Kalkylinkomst' },
      accruedCost: { type: 'number', label: 'Ackumulerad Kostnad' },
      accruedFixedpriceIncome: { type: 'number', label: 'Ackumulerad Fastprisinkomst' },
      accruedHours: { type: 'number', label: 'Ackumulerade Timmar' },
      accruedIncome: { type: 'number', label: 'Ackumulerad Inkomst' },
      accruedOverhead: { type: 'number', label: 'Ackumulerad Omkostnad' },
      accruedProfit: { type: 'number', label: 'Ackumulerad Vinst' },
      accruedProfitAfterOverhead: { type: 'number', label: 'Ackumulerad Vinst Efter Omkostnad' },
      accruedProfitpercent: { type: 'number', label: 'Ackumulerad Vinstprocent' },
      accruedProfitpercentAfterOverhead: { type: 'number', label: 'Ackumulerad Vinstprocent Efter Omkostnad' },
      accruedSupplierinvoiceCost: { type: 'number', label: 'Ackumulerad Leverantörsfaktura Kostnad' },
      accruedSupplierinvoiceIncome: { type: 'number', label: 'Ackumulerad Leverantörsfaktura Inkomst' },
      accruedSupplierinvoiceOverhead: { type: 'number', label: 'Ackumulerad Leverantörsfaktura Omkostnad' },
      accruedSupplierinvoices: { type: 'number', label: 'Ackumulerade Leverantörsfakturor' },
      articleCost: { type: 'number', label: 'Artikelkostnad' },
      articleOverhead: { type: 'number', label: 'Artikelomkostnad' },
      assigner: { type: 'string', label: 'Tilldelare' },
      buyeremail: { type: 'string', label: 'Köparens e-post' },
      buyername: { type: 'string', label: 'Köparens namn' },
      buyerphone: { type: 'string', label: 'Köparens telefon' },
      city: { type: 'string', label: 'Stad' },
      comment: { type: 'string', label: 'Kommentar' },
      company: { type: 'number', label: 'Företag' },
      contractbillings: { type: 'number', label: 'Kontraktsfaktureringar' },
      corporateno: { type: 'string', label: 'Organisationsnummer' },
      cost: { type: 'number', label: 'Kostnad' },
      created: { type: 'string', label: 'Skapad' },
      debitmethod: { type: 'number', label: 'Debiteringsmetod' },
      edinoteExclude: { type: 'number', label: 'Exkludera från EDI-notering' },
      end: { type: 'string', label: 'Slut' },
      freetextsearch: { type: 'string', label: 'Fritextsökning' },
      hours: { type: 'number', label: 'Timmar' },
      id: { type: 'number', autoincrement: true, primary: true, label: 'ID' },
      income: { type: 'number', label: 'Inkomst' },
      invoiceAddress1: { type: 'string', label: 'Fakturaadress 1' },
      invoiceAddress2: { type: 'string', label: 'Fakturaadress 2' },
      invoiceCity: { type: 'string', label: 'Fakturastad' },
      invoiceEmail: { type: 'string', label: 'Faktura-e-post' },
      invoiceIncome: { type: 'number', label: 'Fakturainkomst' },
      invoiceName: { type: 'string', label: 'Fakturanamn' },
      invoicePostcode: { type: 'string', label: 'Fakturapostnummer' },
      invoicemarking: { type: 'string', label: 'Fakturamärkning' },
      invoicenumber: { type: 'string', label: 'Fakturanummer' },
      invoicesum: { type: 'number', label: 'Fakturasumma' },
      lastinvoice: { type: 'string', label: 'Senaste faktura' },
      latestinvoice: { type: 'string', label: 'Senaste faktura' },
      latitude: { type: 'number', label: 'Latitud' },
      longitude: { type: 'number', label: 'Longitud' },
      manager: { type: 'reference', ref: 'salesman', label: 'Handläggare' },
      modified: { type: 'date', label: 'Ändrad' },
      customerNo: { type: 'string', label: 'Kundnummer' },
      noninvoicedAcontoIncome: { type: 'number', label: 'Ej fakturerad Aconto Inkomst' },
      noninvoicedArticleCost: { type: 'number', label: 'Ej fakturerad Artikelkostnad' },
      noninvoicedArticleIncome: { type: 'number', label: 'Ej fakturerad Artikelinkomst' },
      noninvoicedArticleOverhead: { type: 'number', label: 'Ej fakturerad Artikelomkostnad' },
      noninvoicedCalculusIncome: { type: 'number', label: 'Ej fakturerad Kalkylinkomst' },
      noninvoicedFixedpriceIncome: { type: 'number', label: 'Ej fakturerad Fastprisinkomst' },
      noninvoicedHours: { type: 'number', label: 'Ej fakturerade timmar' },
      noninvoicedSupplierinvoiceCost: { type: 'number', label: 'Ej fakturerad Leverantörsfaktura Kostnad' },
      noninvoicedSupplierinvoiceIncome: { type: 'number', label: 'Ej fakturerad Leverantörsfaktura Inkomst' },
      noninvoicedSupplierinvoices: { type: 'number', label: 'Ej fakturerade Leverantörsfakturor' },
      notes: { type: 'string', label: 'Anteckningar' },
      office: { type: 'reference', ref: 'office', label: 'Kontor' },
      openkeycardorders: { type: 'number', label: 'Öppna nyckelkortsorder' },
      overhead: { type: 'number', label: 'Omkostnader' },
      price: { type: 'number', label: 'Pris' },
      priceList: { type: 'string', label: 'Prislista' },
      profit: { type: 'number', label: 'Vinst' },
      profitAfterOverhead: { type: 'number', label: 'Vinst efter omkostnader' },
      profitpercent: { type: 'number', label: 'Vinstprocent' },
      profitpercentAfterOverhead: { type: 'number', label: 'Vinstprocent efter omkostnader' },
      project0: { type: 'number', label: 'Projekt 0' },
      project1: { type: 'number', label: 'Projekt 1' },
      project2: { type: 'number', label: 'Projekt 2' },
      reopenedbysupplierinvoice: { type: 'number', label: 'Återöppnad av leverantörsfaktura' },
      start: { type: 'date', label: 'Start' },
      status: { type: 'enum', values: ['active', 'inactive'], label: 'Status' },
      statuS1: { type: 'date', label: 'Status 1' },
      statuS2: { type: 'date', label: 'Status 2' },
      statuS4: { type: 'date', label: 'Status 4' },
      statuS5: { type: 'date', label: 'Status 5' },
      statuS6: { type: 'date', label: 'Status 6' },
      sumconsumption: { type: 'number', label: 'Summa förbrukning' },
      supplierinvoiceCost: { type: 'number', label: 'Leverantörsfaktura Kostnad' },
      supplierinvoiceOverhead: { type: 'number', label: 'Leverantörsfaktura Omkostnad' },
      supplierinvoices: { type: 'number', label: 'Leverantörsfakturor' },
      workingsite: { type: 'string', label: 'Arbetsplats' },
      voucherCost: { type: 'number', label: 'Kostnad för verifikat' },
      voucherIncome: { type: 'number', label: 'Inkomst för verifikat' },
      xmlcode: { type: 'string', label: 'XML-kod' },
      projectWorkingSite: { type: 'string', label: 'Projektarbetsplats' },
      postCode: { type: 'string', label: 'Postnummer' },
      externalReference: { type: 'string', label: 'Extern referens' },
      externalSystem: { type: 'string', label: 'Externt system' }
    }
  },
  salesman: {
    api: '/api/v1/salesman',
    view: data => `https://app.rekyl.nu/v5/8399/details/salesman/${data.id}`,
    hasPagination: true,
    schema: {
      id: { type: 'number', autoincrement: true, primary: true, label: 'ID' },
      group: { type: 'enum', values: ['A', 'B', 'C'], label: 'Grupp' },
      status: { type: 'enum', values: ['active', 'inactive'], label: 'Status' },
      office: { type: 'reference', ref: 'office', label: 'Kontor' },
      company: { type: 'reference', ref: 'company', label: 'Företag' },
      name: { type: 'string', label: 'Namn' },
      // supervisor: { type: 'reference', ref: 'salesman', label: 'Handledare' },
      corporateNo: { type: 'string', label: 'Organisationsnummer' },
      mobile: { type: 'string', label: 'Mobil' },
      category: { type: 'enum', values: ['A', 'B', 'C'], label: 'Kategori' },
      salaryType: { type: 'enum', values: ['hourly', 'monthly'], label: 'Lönetyp' },
      employeeNumber: { type: 'string', label: 'Anställningsnummer' },
      email: { type: 'string', label: 'E-post' },
      deleted: { type: 'boolean', label: 'Raderad' },
      custom1: { type: 'number', label: 'Anpassad 1' },
      custom2: { type: 'number', label: 'Anpassad 2' },
      custom3: { type: 'number', label: 'Anpassad 3' },
      custom4: { type: 'number', label: 'Anpassad 4' },
      custom5: { type: 'number', label: 'Anpassad 5' },
      custom6: { type: 'number', label: 'Anpassad 6' },
      custom7: { type: 'number', label: 'Anpassad 7' },
      custom8: { type: 'number', label: 'Anpassad 8' },
      custom9: { type: 'number', label: 'Anpassad 9' },
      custom10: { type: 'number', label: 'Anpassad 10' },
      custom11: { type: 'number', label: 'Anpassad 11' },
      custom12: { type: 'number', label: 'Anpassad 12' },
      custom13: { type: 'number', label: 'Anpassad 13' },
      custom14: { type: 'number', label: 'Anpassad 14' },
      custom15: { type: 'number', label: 'Anpassad 15' },
      custom16: { type: 'number', label: 'Anpassad 16' },
      custom17: { type: 'number', label: 'Anpassad 17' },
      custom18: { type: 'number', label: 'Anpassad 18' },
      custom19: { type: 'number', label: 'Anpassad 19' },
      custom20: { type: 'number', label: 'Anpassad 20' },
      custom21: { type: 'number', label: 'Anpassad 21' },
      custom22: { type: 'number', label: 'Anpassad 22' },
      custom23: { type: 'number', label: 'Anpassad 23' },
      custom24: { type: 'number', label: 'Anpassad 24' },
      custom25: { type: 'number', label: 'Anpassad 25' },
      custom26: { type: 'number', label: 'Anpassad 26' },
      custom27: { type: 'number', label: 'Anpassad 27' },
      custom28: { type: 'number', label: 'Anpassad 28' },
      custom29: { type: 'number', label: 'Anpassad 29' },
      custom30: { type: 'number', label: 'Anpassad 30' },
      customText1: { type: 'string', label: 'Anpassad text 1' },
      customText2: { type: 'string', label: 'Anpassad text 2' },
      customText3: { type: 'string', label: 'Anpassad text 3' },
      customText4: { type: 'string', label: 'Anpassad text 4' },
      customText5: { type: 'string', label: 'Anpassad text 5' },
      customText6: { type: 'string', label: 'Anpassad text 6' },
      customText7: { type: 'string', label: 'Anpassad text 7' },
      customText8: { type: 'string', label: 'Anpassad text 8' },
      customText9: { type: 'string', label: 'Anpassad text 9' },
      customText10: { type: 'string', label: 'Anpassad text 10' },
      customText11: { type: 'string', label: 'Anpassad text 11' },
      customText12: { type: 'string', label: 'Anpassad text 12' },
      customText13: { type: 'string', label: 'Anpassad text 13' },
      customText14: { type: 'string', label: 'Anpassad text 14' },
      customText15: { type: 'string', label: 'Anpassad text 15' },
      customText16: { type: 'string', label: 'Anpassad text 16' },
      customText17: { type: 'string', label: 'Anpassad text 17' },
      customText18: { type: 'string', label: 'Anpassad text 18' },
      customText19: { type: 'string', label: 'Anpassad text 19' },
      customText20: { type: 'string', label: 'Anpassad text 20' },
      customText21: { type: 'string', label: 'Anpassad text 21' },
      customText22: { type: 'string', label: 'Anpassad text 22' },
      customText23: { type: 'string', label: 'Anpassad text 23' },
      customText24: { type: 'string', label: 'Anpassad text 24' },
      customText25: { type: 'string', label: 'Anpassad text 25' },
      customText26: { type: 'string', label: 'Anpassad text 26' },
      customText27: { type: 'string', label: 'Anpassad text 27' },
      customText28: { type: 'string', label: 'Anpassad text 28' },
      customText29: { type: 'string', label: 'Anpassad text 29' },
      customText30: { type: 'string', label: 'Anpassad text 30' },
      phone: { type: 'string', label: 'Telefon' },
    }
  },
  office: {
    api: '/api/v1/office',
    hasPagination: false,
    view: null,
    schema: {
      id: { type: 'number', autoincrement: true, primary: true },
      name: { type: 'string' },
    }
  },
  company: {
    api: '/api/v1/company',
    hasPagination: false,
    // view: () => 'https://app.rekyl.nu/v5/8399/details/overlay/settings?menu=63&tab=50',
    schema: {
      id: { type: 'number', autoincrement: true, primary: true, label: 'ID' },
      name: { type: 'string', label: 'Namn' },
      // trashCustomerNo: { type: 'string', label: 'Skräpkundnummer' },
      created: { type: 'date', label: 'Skapad' },
      modified: { type: 'date', label: 'Modifierad' },
      companyName: { type: 'string', label: 'Företagsnamn' },
      address1: { type: 'string', label: 'Adress 1' },
      address2: { type: 'string', label: 'Adress 2' },
      phone: { type: 'string', label: 'Telefon' },
      fax: { type: 'string', label: 'Fax' },
      web: { type: 'string', label: 'Webb' },
      email: { type: 'string', label: 'E-post' },
      plusgiro: { type: 'string', label: 'Plusgiro' },
      bankgiro: { type: 'string', label: 'Bankgiro' },
      corporateidno: { type: 'string', label: 'Organisationsnummer' },
      vatno: { type: 'string', label: 'Momsnummer' },
      logo: { type: 'string', label: 'Logotyp' },
      exportArticlenoAconto: { type: 'string', label: 'Exportartikelnummer Aconto' },
      exportArticlenoFastpris: { type: 'string', label: 'Exportartikelnummer Fastpris' },
      exportArticlenoContractor: { type: 'string', label: 'Exportartikelnummer Entreprenör' },
      exportArticlenoSupplierinvoice: { type: 'string', label: 'Exportartikelnummer Leverantörsfaktura' },
      parent: { type: 'number', label: 'Förälder' },
      exportArticlenoConsumption: { type: 'string', label: 'Exportartikelnummer Förbrukning' },
      exportArticlenoWithoutarticleno: { type: 'string', label: 'Exportartikelnummer Utan artikelnummer' },
      workorderFooter: { type: 'string', label: 'Arbetsorderfot' },
      exportArticlenoServicecar: { type: 'string', label: 'Exportartikelnummer Servicebil' },
      accrualaccounts: { type: 'string', label: 'Periodiseringskonton' },
      accrualVerificationSeries: { type: 'string', label: 'Periodiseringsverifikasionsserie' }
    }
  },
  gpsunit: {
    api: '/api/v1/gpsunit',
    hasPagination: false,
    view: null,
    schema: {
      id: { type: 'number', autoincrement: true, primary: true, label: 'ID' },
      imei: { type: 'string', label: 'IMEI' },
      mobile: { type: 'string', label: 'Mobil' },
      iccId: { type: 'string', label: 'ICC-ID' },
      firmware: { type: 'string', label: 'Firmware' },
      companyId: { type: 'number', label: 'Företags-ID' },
      comment: { type: 'string', label: 'Kommentar' },
      status: { type: 'enum', values: ['active', 'inactive'], label: 'Status' },
      deleted: { type: 'boolean', label: 'Raderad' },
      created: { type: 'date', label: 'Skapad' },
      modified: { type: 'date', label: 'Modifierad' },
      latitude: { type: 'number', label: 'Latitud' },
      longitude: { type: 'number', label: 'Longitud' },
      timestamp: { type: 'date', label: 'Tidsstämpel' },
      heading: { type: 'number', label: 'Riktning' },
      speed: { type: 'number', label: 'Hastighet' },
      flags: { type: 'number', label: 'Flaggor' },
      received: { type: 'date', label: 'Mottagen' },
      satellites: { type: 'number', label: 'Satelliter' },
      gsmSignal: { type: 'number', label: 'GSM-signal' },
      voltage: { type: 'number', label: 'Spänning' },
      minSatellites: { type: 'number', label: 'Minimala satelliter' },
      avgSatellites: { type: 'number', label: 'Genomsnittliga satelliter' },
      maxSatellites: { type: 'number', label: 'Maximala satelliter' },
      minGsmSignal: { type: 'number', label: 'Minimalt GSM-signal' },
      avgGsmSignal: { type: 'number', label: 'Genomsnittligt GSM-signal' },
      maxGsmSignal: { type: 'number', label: 'Maximalt GSM-signal' },
      minVoltage: { type: 'number', label: 'Minimalt spänning' },
      avgVoltage: { type: 'number', label: 'Genomsnittligt spänning' },
      maxVoltage: { type: 'number', label: 'Maximalt spänning' },
      lastFlankIgnitionOff: { type: 'date', label: 'Senaste flank tändning av' },
      lastIgnitionOffVoltage: { type: 'number', label: 'Senaste tändning av spänning' },
      lastZeroVoltage: { type: 'date', label: 'Senaste nollspänning' },
      operator: { type: 'string', label: 'Operatör' },
      sent: { type: 'string', label: 'Skickad' },
      installer: { type: 'string', label: 'Installatör' },
      model: { type: 'string', label: 'Modell' },
      contractStart: { type: 'date', label: 'Kontrakt start' },
      contractEnd: { type: 'date', label: 'Kontrakt slut' },
      monthlyFee: { type: 'number', label: 'Månadsavgift' },
      invoiceIntervalMonths: { type: 'number', label: 'Fakturaintervall månader' },
      invoicedUntil: { type: 'date', label: 'Fakturerad till' },
      workorderInvoice: { type: 'string', label: 'Arbetsorderfaktura' },
      invoiceOffset: { type: 'number', label: 'Fakturaförskjutning' },
      contractMonths: { type: 'number', label: 'Kontraktsmånader' },
      server: { type: 'number', label: 'Server' },
      login: { type: 'string', label: 'Inloggning' },
      password: { type: 'string', label: 'Lösenord' },
      firmwareDate: { type: 'date', label: 'Firmware-datum' },
      startFee: { type: 'number', label: 'Startavgift' },
      startFeeInvoiced: { type: 'string', label: 'Startavgift fakturerad' },
      startFeePreInvoice: { type: 'number', label: 'Startavgift förhandsfaktura' },
      workorderInstallation: { type: 'string', label: 'Arbetsorderinstallation' },
      temperature: { type: 'number', label: 'Temperatur' },
      receivedServer: { type: 'number', label: 'Mottagen server' },
      reseller: { type: 'string', label: 'Återförsäljare' },
      name: { type: 'string', label: 'Namn' },
      icon: { type: 'string', label: 'Ikon' },
      indexation: { type: 'number', label: 'Indexering' },
      indexationStartDate: { type: 'date', label: 'Indexering startdatum' },
      temperature1: { type: 'number', label: 'Temperatur 1' },
      temperature2: { type: 'number', label: 'Temperatur 2' },
      temperature3: { type: 'number', label: 'Temperatur 3' },
      temperature4: { type: 'number', label: 'Temperatur 4' },
      humidity1: { type: 'number', label: 'Fuktighet 1' },
      humidity2: { type: 'number', label: 'Fuktighet 2' },
      humidity3: { type: 'number', label: 'Fuktighet 3' },
      humidity4: { type: 'number', label: 'Fuktighet 4' },
      sensors: { type: 'array', label: 'Sensorer' }
    }
  },
  keycard: {
    api: '/api/v1/keycard',
    view: data => `https://app.rekyl.nu/v5/8399/details/keycard/${data.id}`,
    hasPagination: true,
    schema: {
      cabinet: { type: 'reference', ref: 'cabinet', label: 'Skåp' },
      category: { type: 'number', label: 'Kategori' },
      categoryNosubcategory: { type: 'number', label: 'Kategori utan underkategori' },
      company: { type: 'reference', ref: 'company', label: 'Företag' },
      description: { type: 'string', label: 'Beskrivning' },
      discontinued: { type: 'boolean', label: 'Utgått' },
      id: { type: 'number', autoincrement: true, primary: true, label: 'ID' },
      keyType: { type: 'number', label: 'Nyckeltyp' },
      location: { type: 'string', label: 'Plats' },
      name: { type: 'string', label: 'Namn' },
      keyNumber: { type: 'string', label: 'Nyckelnummer' },
      office: { type: 'reference', ref: 'office', label: 'Kontor' },
      orderDue: { type: 'date', label: 'Beställning förfaller' },
      tag: { type: 'string', label: 'Tagg' },
      created: { type: 'date', label: 'Skapad' },
      modified: { type: 'date', label: 'Modifierad' },
      project: { type: 'string', label: 'Projekt' },
      vehicle: { type: 'number', label: 'Fordon' },
      position: { type: 'number', label: 'Position' },
      checkOutMessage: { type: 'string', label: 'Utcheckningsmeddelande' },
      checkInMessage: { type: 'string', label: 'Incheckningsmeddelande' },
      custom1: { type: 'string', label: 'Anpassad 1' },
      custom2: { type: 'string', label: 'Anpassad 2' },
      custom3: { type: 'string', label: 'Anpassad 3' },
      custom4: { type: 'string', label: 'Anpassad 4' },
      custom5: { type: 'string', label: 'Anpassad 5' },
      custom6: { type: 'string', label: 'Anpassad 6' },
      custom7: { type: 'string', label: 'Anpassad 7' },
      custom8: { type: 'string', label: 'Anpassad 8' },
      custom9: { type: 'string', label: 'Anpassad 9' },
      custom10: { type: 'string', label: 'Anpassad 10' },
      custom11: { type: 'string', label: 'Anpassad 11' },
      custom12: { type: 'string', label: 'Anpassad 12' },
      custom13: { type: 'string', label: 'Anpassad 13' },
      custom14: { type: 'string', label: 'Anpassad 14' },
      custom15: { type: 'string', label: 'Anpassad 15' },
      custom16: { type: 'string', label: 'Anpassad 16' },
      custom17: { type: 'string', label: 'Anpassad 17' },
      custom18: { type: 'string', label: 'Anpassad 18' },
      custom19: { type: 'string', label: 'Anpassad 19' },
      custom20: { type: 'string', label: 'Anpassad 20' },
      custom21: { type: 'string', label: 'Anpassad 21' },
      custom22: { type: 'string', label: 'Anpassad 22' },
      custom23: { type: 'string', label: 'Anpassad 23' },
      custom24: { type: 'string', label: 'Anpassad 24' },
      custom25: { type: 'string', label: 'Anpassad 25' },
      custom26: { type: 'string', label: 'Anpassad 26' },
      custom27: { type: 'string', label: 'Anpassad 27' },
      custom28: { type: 'string', label: 'Anpassad 28' },
      custom29: { type: 'string', label: 'Anpassad 29' },
      custom30: { type: 'string', label: 'Anpassad 30' },
      customtext1: { type: 'string', label: 'Anpassad text 1' },
      customtext2: { type: 'string', label: 'Anpassad text 2' },
      customtext3: { type: 'string', label: 'Anpassad text 3' },
      customtext4: { type: 'string', label: 'Anpassad text 4' },
      customtext5: { type: 'string', label: 'Anpassad text 5' },
      customtext6: { type: 'string', label: 'Anpassad text 6' },
      customtext7: { type: 'string', label: 'Anpassad text 7' },
      customtext8: { type: 'string', label: 'Anpassad text 8' },
      customtext9: { type: 'string', label: 'Anpassad text 9' },
      customtext10: { type: 'string', label: 'Anpassad text 10' },
      customtext11: { type: 'string', label: 'Anpassad text 11' },
      customtext12: { type: 'string', label: 'Anpassad text 12' },
      customtext13: { type: 'string', label: 'Anpassad text 13' },
      customtext14: { type: 'string', label: 'Anpassad text 14' },
      customtext15: { type: 'string', label: 'Anpassad text 15' },
      customtext16: { type: 'string', label: 'Anpassad text 16' },
      customtext17: { type: 'string', label: 'Anpassad text 17' },
      customtext18: { type: 'string', label: 'Anpassad text 18' },
      customtext19: { type: 'string', label: 'Anpassad text 19' },
      customtext20: { type: 'string', label: 'Anpassad text 20' },
      customtext21: { type: 'string', label: 'Anpassad text 21' },
      customtext22: { type: 'string', label: 'Anpassad text 22' },
      customtext23: { type: 'string', label: 'Anpassad text 23' },
      customtext24: { type: 'string', label: 'Anpassad text 24' },
      customtext25: { type: 'string', label: 'Anpassad text 25' },
      customtext26: { type: 'string', label: 'Anpassad text 26' },
      customtext27: { type: 'string', label: 'Anpassad text 27' },
      customtext28: { type: 'string', label: 'Anpassad text 28' },
      customtext29: { type: 'string', label: 'Anpassad text 29' },
      customtext30: { type: 'string', label: 'Anpassad text 30' },
      project1: { type: 'string', label: 'Projekt 1' },
      deleted: { type: 'boolean', label: 'Raderad' },
    }
  },
  cabinet: {
    api: '/api/v1/key-cabinet',
    hasPagination: true,
    view: null,
    schema: {
      name: { type: 'string', label: 'Namn' },
      idcab: { type: 'string', label: 'ID' },
      alcoholLockFrequency: { type: 'number', label: 'Alkoholås frekvens' },
    }
  },
  // 'project-structures': {
  //   api: '/api/v1/project-structures',
  //   schema: {
  //   }
  // }
  // http://localhost:3000/api/v1/time-report
  'time-report': {
    api: '/api/v1/time-report',
    view: data => `https://app.rekyl.nu/v5/8399/details/time-report/${data.id}`,
    hasPagination: true,
    schema: {
      id: { type: 'number', autoincrement: true, primary: true, label: 'ID' },
      workorderId: { type: 'reference', ref: 'workorder', label: 'Arbetsorder ID' },
      date: { type: 'date', label: 'Datum' },
      description: { type: 'string', label: 'Beskrivning' },
      status: { type: 'enum', values: ['reported', 'approved', 'rejected'], label: 'Status' },
      modified: { type: 'date', label: 'Ändrad' },
      created: { type: 'date', label: 'Skapad' }
    }
  }
}

for (const [key, column] of Object.entries(realSchema)) {
  const schema = tables.workorder.schema
  if (schema[key]) {
    // console.log(key, schema[key], column)
  } else {
    // console.warn(`Column ${key} not found in workorder schema`)
  }
}



export default tables